#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov  8 15:57:49 2018

@author: agile
"""

import pandas as pd
from collections import Counter
tx_in = pd.read_csv('tx_in.csv', delimiter=';', names=['txid', 'hashPrevOut', 'indexPrevOut', 'scriptSig', 'seq'])
tx_out = pd.read_csv('tx_out.csv', delimiter=';', names=['txid', 'indexOut', 'value', 'scriptPubKey', 'address'])
trns = pd.read_csv('transactions.csv', delimiter=';', names = ['txid', 'hashBlock', 'version', 'lockTime'])

#print(tx_in[tex]) e1b4dd1c7d9b1687efba4ab9a78e041156e92aff42da9bfeff7f1714c50d44b4



def all_trans_backwards(id):
    receive = tx_out[tx_out['txid'] == id]
    hash_id = tx_in[tx_in['txid'] == receive['txid'].iloc[0]]
    sender = tx_out[(tx_out['txid'] == hash_id['hashPrevOut'].iloc[0])]

    print('id: ', receive['txid'].iloc[0], 'Sender: ', sender['address'].iloc[0], 'Receive: ', receive['address'].values)
    try:
        return sender['txid'].iloc[0]
    except:
        return ''


#idx = all_trans('3b4a4a2959c4930d5ba97fb1bb5059a49b6f912104a042389ae83363b4647ef5')
#idx2 = all_trans(idx)
#print(idx2, '********************************************************')

#idx = '37ef4da4e98bfa46b01a6de50f17a33fa79027146ab39a8ae64610382c48cc64'
#while (len(idx) != 0):
#    idx = all_trans(idx)
    
id = '828ef3b079f9c23829c56fe86e85b4a69d9e06e5b54ea597eef5fb3ffef509fe'    
receive = tx_out[tx_out['txid'] == id]

for add in receive['address']:
    forward = tx_out[(tx_out['address'] == add) & (tx_out['txid'] != id)]
    fwd = tx_out[(tx_out['txid'] == forward['']) & (tx_out['txid'] != id)]
    print(forward['txid'])    